config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/pokemons_purchase/index', to: 'pokemons_purchase#index'
  post '/pokemons_purchase/buy', to: 'pokemons_purchase#buy'

  get '/pokemons_sale/index', to: 'pokemons_sale#index'
  post '/pokemons_sale/sell', to: 'pokemons_sale#sell'

  get '/funds/index', to: 'funds#index'
  post '/funds/buy', to: 'funds#buy'

  get 'history', to: 'history#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  BOUGHT_OPERATION = 'bought'.freeze
  SOLD_OPERATION = 'sold'.freeze

  belongs_to :wallet

  def bought?
    !sold?
  end

  def sold?
    sold
  end

  def pokemon_name_capitalized
    pokemon_name.capitalize
  end

  def operation_capitalized
    operation.capitalize
  end

  def sold_operation?
    operation == SOLD_OPERATION
  end

  def sold_translation
    return '-' if sold_operation?

    sold? ? 'Yes' : 'No'
  end

  def btc_amount_to_s
    btc_amount.to_s
  end

  def visible_btc_amount
    BigDecimal(btc_amount_to_s).to_s[0..9]
  end
end

app/models/user.rb
class User < ApplicationRecord
  DEFAULT_AVATAR = 'charmander-pokemon.png'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :trackable

  has_one :wallet, dependent: :destroy

  def avatar
    read_attribute('avatar') || DEFAULT_AVATAR
  end

  def walelt_usd_amount
    wallet.usd_amount
  end

  def visible_btc_amount
    wallet.visible_btc_amount
  end

  def update_wallet_amount_with_transaction(transaction)
    wallet.update_amount_with_transaction(transaction)
  end

  def to_sell_transactions
    wallet.to_sell_transactions
  end

  def to_sell_transactions_usd_amount
    wallet.to_sell_transactions_usd_amount
  end

  def to_sell_transactions_btc_amount
    wallet.to_sell_transactions_btc_amount
  end

  def wallet_value
    bitcoin_price = bitcoin_price_now
    return { 'CoinApi Failed to Get Bitcoin Value' => 0 } if bitcoin_price.zero?

    {
      'BTC Amount Spent in USD' => to_sell_transactions_usd_amount,
      'BTC Amount Current Value' => to_sell_transactions_btc_amount * bitcoin_price
    }
  end

  def to_sell_transactions_grouped_by_pokemon_name_with_quantity
    return [['No pokemons yet...', 1]] if to_sell_transactions.empty?

    to_sell_transactions.group_by(&:pokemon_name).map do |transaction|
      [transaction[0].capitalize, transaction[1].count]
    end
  end

  def to_sell_transactions_grouped_by_pokemon_name_with_btc_amount
    return [['No pokemons yet...', 1]] if to_sell_transactions.empty?

    to_sell_transactions.group_by(&:pokemon_name).map do |transaction|
      ["#{transaction[0].capitalize} BTC Amount", transaction[1].sum(&:visible_btc_amount)]
    end
  end

  def add_funds(usd_quantity)
    wallet.add_funds(usd_quantity)
  end

  def transactions
    wallet.transactions
  end

  private

  def bitcoin_price_now
    Cryptocurrency::GetBitcoinApi.build.price rescue 0
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :delete_all

  def update_amount_with_transaction(transaction)
    update_with_buy_transaction(transaction) if transaction.bought?
    update_with_sell_transaction(transaction) if transaction.sold?

    self.save!
  end

  def to_sell_transactions
    transactions.where(sold: false)
  end

  def add_funds(usd_quantity)
    self.usd_amount += usd_quantity

    self.save!
  end

  def btc_amount_to_s
    btc_amount.to_s
  end

  def visible_btc_amount
    BigDecimal(btc_amount_to_s).to_s[0..10]
  end

  def to_sell_transactions_usd_amount
    to_sell_transactions.sum(:usd_amount)
  end

  def to_sell_transactions_btc_amount
    to_sell_transactions.sum(:btc_amount)
  end

  private

  def update_with_buy_transaction(transaction)
    raise_wallet_without_enough_funds if not_enough_funds?(transaction)

    self.usd_amount -= transaction.usd_amount
    self.btc_amount += transaction.btc_amount
  end

  def update_with_sell_transaction(transaction)
    self.usd_amount += transaction.usd_amount
    self.btc_amount -= transaction.btc_amount
  end

  def not_enough_funds?(transaction)
    (self.usd_amount - transaction.usd_amount).negative?
  end

  def raise_wallet_without_enough_funds
    raise WalletWithoutEnoughFunds
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  def index; end

  def buy
    current_user.add_funds(usd_quantity)

    redirect_to root_path, notice: 'Funds added successfully!'
  end

  private

  def usd_quantity
    params.require(:usd_quantity).to_f
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  def index
    @all_transactions = current_user.transactions.sort
  end
end

app/controllers/pokemons_purchase_controller.rb
class PokemonsPurchaseController < ApplicationController
  def index
    @pokemons = Pokemon::GetAllApi.build.execute
  rescue PokemonCommunicationError => e
    redirect_to root_path, alert: e.message
  rescue StandardError
    redirect_to_root_path_with_error_message
  end

  def buy
    service = CreateBuyTransaction.build(chosen_pokemon_url)
    transaction = service.execute(current_user)

    redirect_to pokemons_purchase_index_path, notice: "#{transaction.pokemon_name_capitalized} bought successfully!"
  rescue WalletWithoutEnoughFunds,
         PokemonCommunicationError,
         CryptocurrencyCommunicationError => e
    redirect_to pokemons_purchase_index_path, alert: e.message
  rescue StandardError
    redirect_to_root_path_with_error_message
  end

  private

  def chosen_pokemon_url
    params.require('url')
  end

  def redirect_to_root_path_with_error_message
    redirect_to root_path, alert: 'Something went wrong, please try again later.'
  end
end

app/controllers/pokemons_sale_controller.rb
class PokemonsSaleController < ApplicationController
  def index
    @transactions = current_user.to_sell_transactions.sort
    @bitcoin_price = Cryptocurrency::GetBitcoinApi.build.price
  rescue CryptocurrencyCommunicationError => e
    redirect_to root_path, alert: e.message
  rescue StandardError
    redirect_to_root_path_with_error_message
  end

  def sell
    service = CreateSellTransaction.build
    transaction = service.execute(
      user: current_user,
      bitcoin_price: bitcoin_price,
      transaction_id: transaction_id
    )

    redirect_to pokemons_sale_index_path, notice: "#{transaction.pokemon_name_capitalized} sold successfully!"
  rescue ActiveRecord::RecordNotFound
    redirect_to pokemons_sale_index_path, alert: 'Selected transaction not found.'
  rescue StandardError
    redirect_to_root_path_with_error_message
  end

  private

  def transaction_id
    params.require(:transaction_id)
  end

  def bitcoin_price
    params.require(:bitcoin_price).to_f
  end

  def redirect_to_root_path_with_error_message
    redirect_to root_path, alert: 'Something went wrong, please try again later.'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout :resolve_layout

  def create
    super do |resource|
      Wallet.create!(user: resource) if resource.id.present?
    end
  end

  private

  def resolve_layout
    case action_name
    when 'edit', 'update'
      'application'
    else
      'devise'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return render_flash_alert! if flash[:alert].present?
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  def render_flash_alert!
    return '' if flash[:alert].nil?

    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      #{flash[:alert]}
    </div>
    HTML

    html.html_safe
  end
end

app/views/dashboard/index.html.erb
<br>
<br>

<%= pie_chart current_user.to_sell_transactions_grouped_by_pokemon_name_with_btc_amount %>

<br>
<br>

<%= area_chart current_user.wallet_value  %>

<br>
<br>

<%= pie_chart current_user.to_sell_transactions_grouped_by_pokemon_name_with_quantity %>

<br>
<br>

app/views/funds/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card">
    <div class="card-body">
      <%= form_with url: "/funds/buy", method: :post do |form| %>
        <div class="form-group d-flex flex-column" style="width: 295px;">
          <label class="text-format mb-2">How much money do you want to add?</label>
          <%= form.number_field :usd_quantity, class: 'form-control', min: 0.1, step: 0.1 %>
          <%= form.submit "Add", class: 'btn btn-block mt-3', style: 'background-color: #f6a400; color: #8b2900; font-weight: bold;' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/history/index.html.erb
<% if @all_transactions.any? %>
<table class="table margin-bottom-50">
  <thead>
    <tr>
      <th scope="col" class="text-format">ID</th>
      <th scope="col" class="text-format">Pokemon ID</th>
      <th scope="col" class="text-format">Pokemon Name</th>
      <th scope="col" class="text-format">Pokemon Base Experience</th>
      <th scope="col" class="text-format">USD Amount Spent</th>
      <th scope="col" class="text-format">BTC Amount Acquired</th>
      <th scope="col" class="text-format">Operation</th>
      <th scope="col" class="text-format">Sold</th>
    </tr>
  </thead>
  <tbody>
  <% @all_transactions.each do |transaction| %>
    <tr>
      <th><%= transaction.id %></th>
      <td><%= transaction.pokemon_id %></td>
      <td><%= transaction.pokemon_name_capitalized %></td>
      <td><%= transaction.pokemon_base_experience %></td>
      <td><%= number_to_currency(transaction.usd_amount, precision: 6) %></td>
      <td><%= transaction.visible_btc_amount %></td>
      <td><%= transaction.operation_capitalized %></td>
      <td><%= transaction.sold_translation %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
  <h2 class="align-app-body">You don't have Transactions yet...</h2>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] || flash[:alert] %>
  <% if flash[:notice] %>
    <div class="flash-notice" style="position: absolute;">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="flash-alert" style="position: absolute;">
      <%= flash[:alert] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-sm p-2 text-format">
    © Copyright: <a href="https://github.com/DanielFrydman/" target="_blank">Daniel David Frydman</a> · 2023 · v1.0
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light text-format display-list-item" style="border-radius: 0rem 0rem 1rem 1rem;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag('pokecoin_logo.png', style: 'height: 55px; margin: 0px -10px 0px -10px;') %>
    </a>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link text-format" href="/pokemons_purchase/index">Buy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-format" href="/pokemons_sale/index">Sell</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-format" href="/history">History</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-format" href="/funds/index">Add Funds</a>
      </li>
    </ul>
    <div class="d-flex align-items-center" style="cursor: pointer;">
      <div>
        Funds: <%= number_to_currency(current_user.walelt_usd_amount, precision: 4) %> | &nbsp;
      </div> 
      <div>
        Bitcoins: <%= current_user.visible_btc_amount %> | &nbsp;
      </div>
      <a href="/users/edit" class="text-format" style="text-decoration:none;">
        <label style="margin-top: 15px;"> <%= current_user.name %></label>
        <%= image_tag(current_user.avatar, size: "50", style: 'margin: 0px 20px 0px 10px;') %>
      </a>
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-block orange-button', form_class: 'are-you-sure' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeCoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('svgviewer-output.ico') %>
</head>
  <body class="application-body">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeCoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <section class="vh-100" style="background-color: #003A70;">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
              <div class="row g-0">
                <div class="col-md-6 col-lg-5 d-none d-md-block" style="background-color: #ffcb05; border-radius: 1rem 0px 0px 1rem;">
                  <%= image_tag('pokemon-822px.jpg', class: 'img-fluid', style: 'border-radius: 1rem 0 0 1rem;') %>
                </div>
                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                  <div class="card-body p-4 p-lg-5 text-black d-flex align-content-between flex-wrap">
                    <%= yield %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/pokemons_purchase/index.html.erb
<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
  <div class="card">
    <div class="card-body">
      <%= form_with url: "/pokemons_purchase/buy", method: :post do |form| %>
        <div class="form-group d-flex flex-column" style="width: 175px;">
          <label class="text-format">Choose your pokemon:</label>
          <%= form.select :url, @pokemons, class: 'form-control' %>
          <%= form.submit "Buy", class: 'btn btn-block mt-3', style: 'background-color: #f6a400; color: #8b2900; font-weight: bold;' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pokemons_sale/index.html.erb
<% if @transactions.any? %>
<table class="table margin-bottom-50">
  <thead>
    <tr>
      <th scope="col" class="text-format">ID</th>
      <th scope="col" class="text-format">Pokemon Name</th>
      <th scope="col" class="text-format">USD Amount Spent</th>
      <th scope="col" style="color: #e63900; font-weight: bold;">USD Amount Now</th>
      <th scope="col" class="text-format">Button</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <% if transaction.btc_amount * @bitcoin_price > transaction.usd_amount  %>
        <tr class="table-success">
      <% elsif transaction.btc_amount * @bitcoin_price < transaction.usd_amount %>
        <tr class="table-danger">
      <% else %>
        <tr class="table-warning">
      <% end %>
        <th><%= transaction.id %></th>
        <td><%= transaction.pokemon_name_capitalized %></td>
        <td><%= number_to_currency(transaction.usd_amount, precision: 6) %></td>
        <td><%= number_to_currency(transaction.btc_amount * @bitcoin_price, precision: 6) %></td>
        <td><%= button_to 'Sell', pokemons_sale_sell_path, params: { transaction_id: transaction.id, bitcoin_price: @bitcoin_price }, method: :post, class: 'btn btn-block text-format', style: 'background-color: #f6a400;', form_class: 'delete-sell' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h2 class="align-app-body">You don't have Pokemons yet...</h2>
<% end %>